version: "3.3"

services:
  company_service:
    image: marijakljestan/company
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      COMPANY_SERVICE_PORT: 8000
      COMPANY_DB_HOST: mongo
      COMPANY_DB_PORT: 27017
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
